// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-aMf85KKaYpbvoa43kKqbAJvy_J4DFbc',
    appId: '1:479566427899:web:3e09c8e4aff760d065225e',
    messagingSenderId: '479566427899',
    projectId: 'digital-life-app-f82f9',
    authDomain: 'digital-life-app-f82f9.firebaseapp.com',
    storageBucket: 'digital-life-app-f82f9.firebasestorage.app',
    measurementId: 'G-8Y7NWJMG3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkgzyFGhKSHPoThXAVvlfcE7sSTvxUDj0',
    appId: '1:479566427899:android:a3e4ce7bd890357565225e',
    messagingSenderId: '479566427899',
    projectId: 'digital-life-app-f82f9',
    storageBucket: 'digital-life-app-f82f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjKjDx1XMh1zBSVAsNUnRtchoaQJ3Ngtg',
    appId: '1:479566427899:ios:01ab78ebd834565365225e',
    messagingSenderId: '479566427899',
    projectId: 'digital-life-app-f82f9',
    storageBucket: 'digital-life-app-f82f9.firebasestorage.app',
    iosBundleId: 'com.ub.digitalLifeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjKjDx1XMh1zBSVAsNUnRtchoaQJ3Ngtg',
    appId: '1:479566427899:ios:01ab78ebd834565365225e',
    messagingSenderId: '479566427899',
    projectId: 'digital-life-app-f82f9',
    storageBucket: 'digital-life-app-f82f9.firebasestorage.app',
    iosBundleId: 'com.ub.digitalLifeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-aMf85KKaYpbvoa43kKqbAJvy_J4DFbc',
    appId: '1:479566427899:web:90753ae689e2b39465225e',
    messagingSenderId: '479566427899',
    projectId: 'digital-life-app-f82f9',
    authDomain: 'digital-life-app-f82f9.firebaseapp.com',
    storageBucket: 'digital-life-app-f82f9.firebasestorage.app',
    measurementId: 'G-BZ4N3TCTFG',
  );
}
